name: Deploy to Heroku server

on: 
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - name: install npm
      run: sudo npm install
    - name: build
      run: npm run build

  deploy:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v3
    - name: Add Heroku remote
      run: 
        git remote add heroku https://heroku:${{ secrets.HEROKU_API_KEY }}@git.heroku.com/${{ secrets.HEROKU_APP_NAME }}.git
    - name: push to Heroku
      run: git push -f heroku main
