name: Deploy to Heroku server

on: 
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v3

      - name: install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: npm

      - name: install npm dependencies
        run: npm install

      - name: npm init
        run: npm init -y

      - name: run build
        run: npm run build --if-present

  deploy:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v3
    - name: Add Heroku remote
      run: 
        git remote add heroku https://heroku:${{ secrets.HEROKU_API_KEY }}@git.heroku.com/${{ secrets.HEROKU_APP_NAME }}.git
    - name: push to Heroku
      run: git push -f heroku main
