name: Deploy to Heroku server

on: 
  push:
    branches:
      - main

jobs:
  build:
    env:
      HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: Push to Heroku
      run: heroku git:remote -a geo-pwa