name: CI/CD

on: 
  push:
    branches:
      - main

jobs:

  # zap_scan:
  #   runs-on: ubuntu-latest
  #   name: Scan ZAP website
  #   steps:
  #     - name: ZAP Scan
  #       uses: zaproxy/action-baseline@v0.6.1
  #       with:
  #         target: 'https://geo-pwa.herokuapp.com'

  build:
    # needs: zap_scan
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2

      - name: install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: npm

      - name: install npm dependencies
        run: npm install

      - name: npm init
        run: npm init -y

      - name: npm run start
        env:
          CI: false
        run: npm run build --if-present


  deploy:
    needs: build
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    
    - name: fetch history of shallow clone
      run: git fetch --unshallow

    - name: Add Heroku remote
      run: 
        git remote add heroku https://heroku:${{ secrets.HEROKU_API_KEY }}@git.heroku.com/${{ secrets.HEROKU_APP_NAME }}.git

    - name: push to Heroku
      run: git push -f heroku main
