name: Deploy to Heroku server

on: 
  push:
    branches:
      - main

jobs:
  deploy:
    env:
      HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v3
    - name: Add Heroku remote
      run: 
        git remote add heroku https://heroku:$HEROKU_API_KEY@git.heroku.com/${{ secrets.HEROKU_APP_NAME }}.git
    - name: push to Heroku
      run: git push -f heroku main
